{% set name = "peft" %}
{% set version = "0.19.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/huggingface/peft/archive/v{{ version }}.tar.gz
  sha256: 55c804e925796814fb7b6242e9e8698049591cdaf4706e69646b01add9c5844c

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - numpy >=1.17
    - packaging >=20.0
    - psutil
    - pyyaml
    - pytorch >=1.13.0
    - transformers
    - tqdm
    - accelerate >=0.21.0
    - safetensors
    # accelerate -> huggingface_accelerate
    - huggingface_accelerate >=0.21.0
    - huggingface_hub >=0.25.0

test:
  source_files:
    - tests
  imports:
    - peft
  commands:
    - pip check
    - pytest -v tests/test_config.py tests/test_mapping.py tests/test_bufferdict.py -k "not pretrained and not remote"
  requires:
    - pip
    - pytest
    - parameterized

about:
  home: https://github.com/huggingface/peft
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  dev_url: https://github.com/huggingface/peft
  doc_url: https://huggingface.co/docs/peft/index
  summary: Parameter-Efficient Fine-Tuning (PEFT)
  description: |
    Parameter-Efficient Fine-Tuning (PEFT) methods enable efficient adaptation of pre-trained language models (PLMs) to various
    downstream applications without fine-tuning all the model's parameters. Fine-tuning large-scale PLMs is often prohibitively costly.
    In this regard, PEFT methods only fine-tune a small number of (extra) model parameters, thereby greatly decreasing the computational
    and storage costs. Recent State-of-the-Art PEFT techniques achieve performance comparable to that of full fine-tuning.

extra:
  recipe-maintainers:
    - markw77
